/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co.eventmesh.samples.helloperf;


import java.util.Arrays;
import java.util.concurrent.CountDownLatch;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.solacesystems.jcsmp.JCSMPException;
import com.solacesystems.jcsmp.XMLMessageProducer;


public class App {
	static private Logger logger = LoggerFactory.getLogger(App.class);

    public String getGreeting() {
        return "Hello world.";
    }

    
    public static void main(String[] args) throws Exception {
    	logger.info("App Starting");
    	Configuration.setupDefaults(args);

    	int msgCount = Integer.parseInt(Configuration.getDefaults().get("msgcount"));

    	int publishThreads = Integer.parseInt(Configuration.getDefaults().get("publishthreads"));    		
    	
    	CountDownLatch startSignal = new CountDownLatch(1);
    	
        CountDownLatch doneSignal = new CountDownLatch(msgCount*publishThreads);
    	
    	
    	if (Configuration.getDefaults().get("consume") != null) {
    		startConsuming(startSignal, doneSignal);
    	}
    	Stopwatch watch = new Stopwatch("Messages Consumed:");
    	
    	if (Configuration.getDefaults().get("publish") != null) {
    		startPublishing(startSignal, doneSignal);    		
    	}
    	
    	
    	
//    	new Thread(new PublishThread(5, "Hello World"), "publish-thread").start();
//    	System.out.println("0:" + args[0] + "1:" + args[1] + "2:" + args[2]);
//    	
//    	HashMap<String, String> parsedArgs = Configuration.getArguments(args);    		
//        System.out.println("ParsedArgs = " + parsedArgs);
//        SimpleThreadPool.main(args);
    	doneSignal.await();
    	logger.info(watch.toString());

    	Thread.sleep(5000);
    }
    
    
    public static void startConsuming(CountDownLatch startSignal, CountDownLatch doneSignal) throws JCSMPException, InterruptedException {

    	int consThreadCount = Integer.parseInt(Configuration.getDefaults().get("consumethreads"));    		

    	String consumequeue = Configuration.getDefaults().get("consumequeue");
    	String respondtopic = Configuration.getDefaults().get("respondtopic");

    	
    	for (int i = 0; i < consThreadCount; i++) {
    		startConsumingThread(startSignal, doneSignal, i, consumequeue, respondtopic  );
    	}
    	
    }
    
    
    public static String createString(int stringLength){
        
        char[] charArray = new char[stringLength];
        char ch = 'A';
        Arrays.fill(charArray, ch);        
        return new String(charArray);
    }
    
    public static void startPublishing(CountDownLatch startSignal, CountDownLatch doneSignal) throws JCSMPException {
    	
    	int threadCount = Integer.parseInt(Configuration.getDefaults().get("publishthreads"));    		    	
    	int messagesize = Integer.parseInt(Configuration.getDefaults().get("messagesize"));    		

    	for (int i = 0; i < threadCount; i++) {

    		startPublishingThread(startSignal, doneSignal,i, messagesize);    		
    	}

    	
    }
    
    
    public static void startPublishingThread(CountDownLatch startSignal, CountDownLatch doneSignal,
    		int threadNo, int messageSize) throws JCSMPException {
    	int repeatCount = Integer.parseInt(Configuration.getDefaults().get("msgcount"));
    	String publishTopic = Configuration.getDefaults().get("publishtopic");
    	String publishmode = Configuration.getDefaults().get("publishmode");
    	String messageStr = createString(messageSize);

    	PublishThread publishThread = new PublishThread(publishTopic, repeatCount, messageStr, publishmode);
    	PublishEventHandler handler = new PublishEventHandler();
    	XMLMessageProducer prod = SolacePublisherFactory.getProducer(handler);
    	publishThread.setProducerListener(prod, handler);
    	
    	new Thread(publishThread, "publish-thread-" + threadNo).start();    	
    }

    
    public static void startConsumingThread(CountDownLatch startSignal, CountDownLatch doneSignal,
    		int threadNo, String queueName, String respondtopic) throws JCSMPException, InterruptedException {
    	logger.info("startConsuming THread " + queueName + " " + respondtopic) ;
    	String respondmode = Configuration.getDefaults().get("respondmode");

    	ConsumeThread consumeThread = new ConsumeThread(queueName);
    	
    	ConsumeMessageListener handler = new ConsumeMessageListener(threadNo, doneSignal, respondtopic, respondmode);    	
    	consumeThread.setConsumerListener(handler);

    }

    
    
    
}
