/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co.eventmesh.samples.helloperf;

import java.util.HashMap;

import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.DefaultParser;
import org.apache.commons.cli.HelpFormatter;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.ParseException;

public class Configuration {
	private static Options options = optionsBuilder();

    public static void Usage() {
    	System.err.println("Usage:");
    	// automatically generate the help statement
    	HelpFormatter formatter = new HelpFormatter();
    	formatter.printHelp( "App", options );
    	
    }
    
    
    private static Options optionsBuilder() {
    	Options options = new Options();
       	
    	options.addOption(Option.builder("h")
   		     .required(false)
   		     .desc("host FQDN")
   		     .longOpt("hostname")
   		     .numberOfArgs(1)
   		     .build());
    	options.addOption(Option.builder("u")
      		     .required(true)
      		     .desc("username")
      		     .longOpt("username")
      		     .numberOfArgs(1)
      		     .build());
    	options.addOption(Option.builder("p")
      		     .required(true)
      		     .desc("password")
      		     .longOpt("password")
      		     .numberOfArgs(1)
      		     .build());
    	options.addOption(Option.builder("n")
      		     .required(true)
      		     .desc("port number")
      		     .longOpt("port")
      		     .numberOfArgs(1)
      		     .build());
    	options.addOption(Option.builder("w")
     		     .required(true)
     		     .desc("publish ack window")
     		     .longOpt("pubackwindow")
     		     .numberOfArgs(1)
     		     .build());
    	options.addOption(Option.builder("v")
     		     .required(false)
     		     .desc("verbose")
     		     .longOpt("verbose")
     		     .numberOfArgs(0)
     		     .build());
    	return(options);
    	
    }
    
    private static void updateArgument(String key, HashMap<String, String> hmap, CommandLine cmd) {
    	if (cmd.hasOption("hostname"))
    		hmap.put("hostname", cmd.getOptionValue("hostname"));
    	System.out.println(hmap);
    }
    
    public static HashMap<String, String> getArguments(String[] args) { 
    	HashMap<String, String> hmap = new HashMap<String,String>();
    	hmap.put("hostname", "localhost");
    	hmap.put("port", "55555");
    	
    	CommandLineParser parser = new DefaultParser();
    	CommandLine cmd;
		try {
			cmd = parser.parse( options, args);
	    	hmap.put("password", cmd.getOptionValue("password"));
	    	updateArgument("hostname", hmap, cmd);
	    	updateArgument("username", hmap, cmd);
	    	return(hmap);
		} catch (ParseException e) {
    		System.err.println("Error in command line arguments. " + e.getMessage());
    		Usage();
    		System.exit(1);

		}
		throw new RuntimeException("Unknown Error");
    	

    	
    	
    }
    
}
