/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co.eventmesh.samples.helloperf;

import java.util.HashMap;

import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.DefaultParser;
import org.apache.commons.cli.HelpFormatter;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.ParseException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Configuration {
	static private Logger logger = LoggerFactory.getLogger(Configuration.class);

	private static Options options = optionsBuilder();
	private static HashMap<String, String> hmap = new HashMap<String,String>();
	
	public static final int PUBLISH_COUNT = 1;
	public static final int THREAD_COUNT = 1;
	public static final int MESSAGE_SIZE = 1;
	public static final int CONSUMER_THREAD_COUNT = 2;
	

    public static void Usage() {
    	System.err.println("Usage:");
    	// automatically generate the help statement
    	HelpFormatter formatter = new HelpFormatter();
    	formatter.printHelp( "App", options );
    	
    }
    
    
    private static Options optionsBuilder() {
    	Options options = new Options();
       	
    	options.addOption(Option.builder("h")
   		     .required(false)
   		     .desc("host FQDN")
   		     .longOpt("hostname")
   		     .numberOfArgs(1)
   		     .build());
    	options.addOption(Option.builder("u")
      		     .required(false)
      		     .desc("username")
      		     .longOpt("username")
      		     .numberOfArgs(1)
      		     .build());
    	options.addOption(Option.builder("p")
      		     .required(false)
      		     .desc("password")
      		     .longOpt("password")
      		     .numberOfArgs(1)
      		     .build());
    	options.addOption(Option.builder("o")
     		     .required(true)
     		     .desc("publishcount")
     		     .longOpt("publishcount")
     		     .numberOfArgs(1)
     		     .build());
    	options.addOption(Option.builder("v")
     		     .required(true)
     		     .desc("vpn name")
     		     .longOpt("vpn")
     		     .numberOfArgs(1)
     		     .build());
    	options.addOption(Option.builder("j")
    		     .required(true)
    		     .desc("publish topic")
    		     .longOpt("publishtopic")
    		     .numberOfArgs(1)
    		     .build());
    	options.addOption(Option.builder("t")
      		     .required(false)
      		     .desc("thread count")
      		     .longOpt("threadcount")
      		     .numberOfArgs(1)
      		     .build());
    	options.addOption(Option.builder("z")
     		     .required(false)
     		     .desc("message size")
     		     .longOpt("messagesize")
     		     .numberOfArgs(1)
     		     .build());
    	options.addOption(Option.builder("h")
      		     .required(false)
      		     .desc("host FQDN")
      		     .longOpt("hostname")
      		     .numberOfArgs(1)
      		     .build());
    	options.addOption(Option.builder("i")
     		     .required(true)
     		     .desc("Consumer Thread Count")
     		     .longOpt("consthreadcount")
     		     .numberOfArgs(1)
     		     .build());
    	options.addOption(Option.builder("aa")
     		     .required(true)
     		     .desc("consumequeuename")
     		     .longOpt("consumequeuename")
     		     .numberOfArgs(1)
     		     .build());
    	options.addOption(Option.builder("bb")
    		     .required(true)
    		     .desc("publishouttopic")
    		     .longOpt("publishouttopic")
    		     .numberOfArgs(1)
    		     .build());
    	options.addOption(Option.builder("cc")
   		     .required(false)
   		     .desc("consume")
   		     .longOpt("consume")
   		     .numberOfArgs(0)
   		     .build());
    	options.addOption(Option.builder("pp")
      		     .required(false)
      		     .desc("publish")
      		     .longOpt("publish")
      		     .numberOfArgs(0)
      		     .build());


    	
    	
    	
//    	options.addOption(Option.builder("w")
//     		     .required(true)
//     		     .desc("publish ack window")
//     		     .longOpt("pubackwindow")
//     		     .numberOfArgs(1)
//     		     .build());
//    	options.addOption(Option.builder("v")
//     		     .required(false)
//     		     .desc("verbose")
//     		     .longOpt("verbose")
//     		     .numberOfArgs(0)
//     		     .build());
    	return(options);
    	
    }
    
    private static void updateArgument(String key, CommandLine cmd) {
    	String val = null;
    	if (cmd.hasOption(key)) {
    		val = cmd.getOptionValue(key) != null ? cmd.getOptionValue(key):"1";
    	}
    	hmap.put(key, val);
    }
    
    public static HashMap<String, String> setupDefaults(String[] args) { 
//    	hmap.put("hostname", "localhost");
//    	hmap.put("port", "55555");
    	
    	CommandLineParser parser = new DefaultParser();
    	CommandLine cmd;
		try {
			cmd = parser.parse( options, args);
	    	updateArgument("publishcount", cmd);
	    	updateArgument("hostname", cmd);
	    	updateArgument("publishtopic", cmd);
	    	
	    	updateArgument("username", cmd);
	    	updateArgument("password", cmd);
	    	updateArgument("vpn", cmd);
	    	updateArgument("port", cmd);

	    	updateArgument("threadcount", cmd);
	    	updateArgument("messagesize", cmd);

	    	updateArgument("consumequeuename", cmd);
	    	updateArgument("publishouttopic", cmd);
	    	updateArgument("consthreadcount", cmd);
	    	
	    	updateArgument("consume", cmd);
	    	updateArgument("publish", cmd);

	    	
	    	return(hmap);
		} catch (ParseException e) {
    		logger.error("Error in command line arguments. " + e.getMessage());
    		Usage();
    		System.exit(1);
		}
		throw new RuntimeException("Unknown Error");
    	
    }

    public static HashMap<String, String> getDefaults() { 
    	return hmap;
    	
    }

}
